// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/swordandtea/fhwh/biz/config"
	"github.com/swordandtea/fhwh/biz/service"
)

func Init() {
	if err := config.InitConfig("conf/config.yaml"); err != nil {
		panic(err)
	}

	if err := service.InitDB(); err != nil {
		panic(err)
	}
}

func main() {
	Init()

	h := server.Default()

	register(h)
	h.Spin()
}
