// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/swordandtea/fhwh/biz/config"
	"github.com/swordandtea/fhwh/biz/service"
)

func Init() {
	if err := config.InitConfig("conf/config.yaml"); err != nil {
		panic(err)
	}
	mysqlConf := config.GlobalConfig.Mysql
	if err := service.InitDB(mysqlConf.DSN); err != nil {
		panic(err)
	}

	mailServiceConf := config.GlobalConfig.EmailService
	if err := service.InitMailService("", mailServiceConf.Sender, mailServiceConf.AuthCode, mailServiceConf.Host, mailServiceConf.Port); err != nil {
		panic(err)
	}
}

func main() {
	Init()

	h := server.Default()

	register(h)
	h.Spin()
}
