local:
  log:
    level: DEBUG
  mysql:
    dsn: 'root:123456@tcp(localhost:3306)/fhwf?charset=utf8mb4&parseTime=true'

deploy:
  log:
    level: INFO
    mysql:
      dsn: '<replace with your online mysql dsn>'